# Generated by Django 4.0.2 on 2022-05-25 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_category_contact_countries_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='price_for_one_TON',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_in_TON',
        ),
    ]
