# Generated by Django 4.0.2 on 2022-05-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_category_countries_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countries',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='countries',
        ),
        migrations.AddField(
            model_name='product',
            name='countries',
            field=models.ManyToManyField(to='web.Countries'),
        ),
    ]
