# Generated by Django 4.0.2 on 2022-05-24 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_countries_options_remove_product_countries_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='quantity_in_TON',
        ),
    ]
